### PR TITLE
Updated RAML for listing

### PR DESCRIPTION
**Pull request by kingbrendann**

### CODE REVIEW

**Comment by kingbrendann** [comment]
Addresses https://github.com/More2Life/m2l-server/issues/34

**Comment by dodgertodd** [comment]
After updating RAML, remember to update the HTML. We can probably get Travis to do this for us eventually.

raml2html docs/m2l.raml > docs/index.html

**Review by dodgertodd — APPROVED** [review]
I guess my question right now is that this change would mean that every single product from Square is going to show up in the feed, as opposed to the Product collection being products, and the Listing collection being the way we get the products we want to be in the feed.

**Comment by kingbrendann** [comment]
I'm not really sure why that's a problem. Every item in the square store should be in the feed. If it's for sale, we should sell it. How else would we designate a product should be part of a listing?

**Pull request merged**
